name: OrbitalStrike
version: 1.3.1
main: me.fairyzz.orbitalstrike.OrbitalStrikePlugin
api-version: 1.21
commands:
  orbital:
    description: Get an orbital strike rod
    usage: /orbital <nuke|stab|dogs>
    permission: orbital.use
    permission-message: §cYou don't have permission!